# if cancel is set, removes the list from the public interface
bool cancel
# list of connections to add/cancel to watchlist
Connection[] watchlist

---

# updated watchlist after this interaction
bool success
Connection[] watchlist
