# if cancel is set, stops advertising all connections
bool cancel
# list of connections to exclude apart from default blacklists
PublicRule[] blacklist

---

int8 result
# The overall blacklist used (default + supplied)
PublicRule[] blacklist
