# Service to flip a single connection to a remote gateway
#
# Todo - we might expand this to incorporate
#
# a) flip multiple connections to a remote gateway
# b) flip multiple connections to multiple remote gateways
#
# I suspect that will just complicate the service too much though.
# Since it's not high volume traffic, sending a few services instead
# of just one isn't a massive disadvantage.
#

# The target recipient of the flip
string gateway

# Connection type - use string constants defined in Connection.msg
string type

# Fully qualified local connection name 
string name

# Optional fully qualified node name (to further refine the selection)
# This is necessary, for instance, if you have multiple subscribers
# publishing to a single topic.
string node_name

# If specified, the connection name will be remapped to this name
# in the remote gateway's workspace. If unspecified it will simply
# flip with the original name, but namespaced under the unique gateway name. 
# e.g. gateway1:/chatter -> gateway2:/gateway1/chatter. This is to help
# avoid conflicts.
 
string remapped_name

# if cancel is set, removes the connection from the flipped interface
bool cancel

---

# Return a verbose error string to help with debugging if success fails.
# Strings defined in GatewayError.msg
int8 result
string error_message 

# Todo: return an updated flip watchlist