---
###### Gateway information ######

string name
bool connected
string hub_name

###### Public Interface ######

PublicRule[] public_watchlist
PublicRule[] public_interface

###### Flipped Interface ######

FlipRule[] flip_watchlist
FlipRule[] flipped_connections

