---
###### Gateway information ######

string name
bool connected
string hub_name

###### Public Interface ######

Rule[] public_watchlist
Rule[] public_interface

###### Flipped Interface ######

Rule[] flipped_connections
Rule[] flip_watchlist

###### Foreign Interface ######

RemoteRule[] flipped_in_connections
# RemoteRule[] pulled_connections
