---
###### Gateway information ######

string name
bool connected
string hub_name

###### Public Interface ######

###### Flipped Interface ######

FlipRule[] flipped_connections
FlipRule[] flip_rules
FlipPattern[] flip_patterns

