# Use to list all remote public interfaces. 
#
# Could specialise this to return a list of public interfaces
# corresponding to a specified subset of 'all', but have no use
# case for this yet. Use string[] gateway_names for the request in
# this case
#

---
PublicInterface[] public_interfaces
