# Service to flip a single connection to a remote gateway
#
# Todo - we might expand this to incorporate
#
# a) flip multiple connections to a remote gateway
# b) flip multiple connections to multiple remote gateways
#
# I suspect that will just complicate the service too much though.
# Since it's not high volume traffic, sending a few services instead
# of just one isn't a massive disadvantage.
#

FlipRule rule

# if true, attempt to cancel an existing flip rather than creating it
bool cancel

---

# Return a verbose error string to help with debugging if success fails.
# Strings defined in GatewayError.msg
int8 result
string error_message

# We may not need to burden it with this.
# FlipRule[] current_flip_rules
