---
# Unique name (comes from the gateway systems unique naming system)
string name

# Status modes
# Valid string constants are provided by concert_msgs/Constants.msg
string client_status
string app_status

# Depracate this
string status
