string                      name
string                      description
string                      author
int16                       status
bool                        enabled
uint16                      priority
uuid_msgs/UniqueID          uuid
uint16                      launcher_type
string                      launcher
string                      interactions

# Service TYPE
uint16 TYPE_ROSLAUNCH = 1
uint16 TYPE_CUSTOM    = 2
