string                      name
string                      description
string                      author
int16                       status
bool                        enabled
uint16                      priority
uuid_msgs/UniqueID          uuid
uint16                      launcher_type
string                      launcher
string                      interactions

# Service TYPE
string TYPE_ROSLAUNCH = roslaunch
string TYPE_CUSTOM    = custom

