# Constants used for many of the concert messages and services.

######################## Platform Triple ########################

string PLATFORM_ANY=*
string PLATFORM_LINUX=linux
string PLATFORM_WINDOZE=windoze
string PLATFORM_ANDROID=android

string SYSTEM_CUSTOM=custom
string SYSTEM_ROS=ros
string SYSTEM_OPROS=opros

# Valid robot types, though this is totally not
# official, and we aren't relying on it.
string ROBOT_ANY=*
string ROBOT_PC=pc
string ROBOT_ROBOSEM=robosem
string ROBOT_KOBUKI=kobuki
string ROBOT_TURTLEBOT=turtlebot

######################### Status Modes ##########################

string CONCERT_CLIENT_STATUS_AVAILABLE=available
string CONCERT_CLIENT_STATUS_CONCERT=concert_mode
string CONCERT_CLIENT_STATUS_PAIRED=paired_mode

string APP_STATUS_STOPPED=stopped
string APP_STATUS_RUNNING=running
